### ISSUE TITLE
Why `getLength` instead of `length`?

### ISSUE THREAD

**Issue by ckknight** [rpowelll/bs-enzyme#1]
Especially given the terseness of other operations such as `html` or `text`, `length` fits into that paradigm, though of course fails it compared to `getNode`.

Also, it's what the property actually is in JavaScript. It just is accessed differently in JS than BS, so that can be abstracted away such that BS users don't have to care.

This is all highly subjective and I don't know if there's a standard in place for this yet.

**Comment by rpowelll** [comment]
Definitely agree with this, I've changed it on `master`, so expect the change to show up in 0.2
