### ISSUE TITLE
Error on missing `enzyme-adapter-react-16`

### ISSUE THREAD

**Issue by yatesco** [rpowelll/bs-enzyme#3]
(NOTE: this is almost certainly me as I am flailing around in the dark randomly smashing keys hoping something works!)

I installed a new project, followed your instructions but I get the following error:
```
npm test            

> reason-to-do@ test /Users/coliny/Dev/wurble
> jest

 FAIL  lib/js/__tests__/Example_test.js
  ● Test suite failed to run

    Cannot find module 'enzyme-adapter-react-16' from 'Example_test.js'

       7 | var TodoApp            = require("../src/TodoApp.js");
       8 | var ReasonReact        = require("reason-react/lib/js/src/reasonReact.js");
    >  9 | var EnzymeAdapterReact = require("enzyme-adapter-react-16");
      10 | 
      11 | Enzyme.configureEnzyme(new EnzymeAdapterReact());
      12 | 
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:194:17)
      at Object.<anonymous> (lib/js/__tests__/Example_test.js:9:26)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.424s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```
If I manually run `npm install --save-dev enzyme-adapter-react-16` then it works. Shall I issue a PR with updated `README.md`?

**Comment by rpowelll** [comment]
Yeah so the idea here was that, as of version 3, Enzyme supports various adapters for use with different libraries / versions of libraries. There's more info on it in [the Enzyme README](https://github.com/airbnb/enzyme#upgrading-from-enzyme-2x-or-react--16). 

That said, I don't think people are likely to be using anything other than ReasonReact with bs-enzyme, so it might be sensible to make the adapter for that an explicit dependency. Either that or update the README to be more explicit about requiring it.

**Comment by rpowelll** [comment]
Alright, I've gone ahead and updated the README to be more explicit about requiring an adapter, using the example of `enzyme-adapter-react-16`

**Comment by yatesco** [comment]
Thanks @rpowelll :-).
